ICONOS = {
    "logo": "🧠",
    "dashboard": "📊",
    "tickets": "🎫",
    "flujo": "🤖",
    "reportes": "📈",
    "config": "⚙️",
    "salir": "↩",
    "registro": "📝",
    "nlp": "💬",
    "clasificacion": "🏷️",
    "derivacion": "🔀",
    "validacion": "✅",
    "tecnica": "🛠️",
    "cierre": "🏁",
    "alerta": "🚨",
    "sla": "⏱️",
    "ia": "✨",
}
