TICKETS_DEMO = [
    {
        "id": "TK-1024",
        "titulo": "Servidor de facturación sin respuesta",
        "categoria": "Infraestructura",
        "prioridad": "Crítica",
        "estado": "Derivado",
        "sla": "18 min restantes",
        "confianza": 96,
        "equipo": "NOC Nivel 2",
        "fecha": "Hoy 09:12",
    },
    {
        "id": "TK-1025",
        "titulo": "Error al iniciar sesión en CRM",
        "categoria": "Aplicaciones",
        "prioridad": "Alta",
        "estado": "En atención",
        "sla": "1 h 45 min",
        "confianza": 91,
        "equipo": "Soporte Apps",
        "fecha": "Hoy 09:34",
    },
    {
        "id": "TK-1026",
        "titulo": "Lentitud intermitente en red interna",
        "categoria": "Redes",
        "prioridad": "Media",
        "estado": "Validación",
        "sla": "5 h 20 min",
        "confianza": 84,
        "equipo": "Redes Corporativas",
        "fecha": "Hoy 10:02",
    },
    {
        "id": "TK-1027",
        "titulo": "Solicitud de acceso a tablero BI",
        "categoria": "Accesos",
        "prioridad": "Baja",
        "estado": "Registrado",
        "sla": "22 h",
        "confianza": 78,
        "equipo": "Mesa de Ayuda",
        "fecha": "Hoy 10:18",
    },
    {
        "id": "TK-1028",
        "titulo": "Caída de VPN para usuarios remotos",
        "categoria": "Seguridad",
        "prioridad": "Alta",
        "estado": "Análisis IA",
        "sla": "2 h 10 min",
        "confianza": 89,
        "equipo": "Ciberseguridad",
        "fecha": "Hoy 10:31",
    },
]
